{% set version = "1.6.3" %}

package:
  name: pylibmc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylibmc/pylibmc-{{ version }}.tar.gz
  sha256: eefa46115537abad65fbe2e032acd1b3463d9bf9e335af4b0916df4e4d3206e0

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cyrus-sasl
    - libmemcached
    - pip
    - python
    - setuptools
    - zlib
  run:
    - libmemcached
    - python

test:
  imports:
    - _pylibmc
    - pylibmc

about:
  home: https://github.com/lericson/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Quick and small memcached client for Python

extra:
  recipe-maintainers:
    - bollwyvl
